defmodule Steward.Resource.Validations.RequireWitness do
  @moduledoc """
  The Witness Pattern, made real (docs/tech_spec.md §4.1: "making the
  borrow checker unbypassable... every Ash action generated by the DSL
  therefore requires a borrow_token in its changeset context. The Spark
  compiler injects this requirement automatically... There is no opt-out
  path at the resource layer"; CLAUDE.md invariant 1: "No unwitnessed
  access").

  `Steward.Resource.Transformers.RequireWitness` attaches one instance of
  this validation, globally, to every resource that uses the
  `Steward.Resource` extension — never hand-wired per action, so an
  author cannot forget it the way a per-action `change` could be
  forgotten.

  Implements `supports/1` for `Ash.Changeset` and `Ash.ActionInput` so
  the same module covers create/update/destroy and generic actions alike
  (see `Steward.Resource.Transformers.RequireWitness` for why `:read` is
  deliberately excluded).

  ## The token is verified, not merely present

  `context[:steward][:borrow_token]` is checked against
  `Steward.ResourceServer.verify_borrow/3`, the authority that issued it.
  Presence alone is not enough, because presence alone is trivially
  forgeable — `context: %{steward: %{borrow_token: make_ref()}}` would
  otherwise satisfy a borrow checker the spec calls unbypassable. A token
  is accepted only when all three hold:

    * the borrow is still held (not released, timed out, or invented),
    * the process running this action is the process the borrow was
      granted to, and
    * the borrow was taken on this resource — i.e. on a
      `{__MODULE__, resource_id}` key.

  Anything else is `{:error, :unborrowed_access}`, the same structured
  reason a missing token produces: a caller who cannot prove custody is
  in the same position as one who never claimed it.

  Both `validate/3` and `atomic/3` are implemented identically: the check
  only inspects `context` and process identity, never resource
  attributes, so it needs no database expression and is atomic-compatible
  by construction — no `require_atomic? false` needed on account of this
  validation.
  """

  use Ash.Resource.Validation

  alias Steward.Errors.UnborrowedAccess
  alias Steward.ResourceServer

  @impl true
  def supports(_opts), do: [Ash.Changeset, Ash.ActionInput]

  @impl true
  def validate(changeset_query_or_input, _opts, _context) do
    check(changeset_query_or_input)
  end

  @impl true
  def atomic(changeset_query_or_input, _opts, _context) do
    check(changeset_query_or_input)
  end

  defp check(%{resource: resource, context: context}) do
    with borrow_token when not is_nil(borrow_token) <-
           get_in(context, [:steward, :borrow_token]),
         {:ok, _entry} <- ResourceServer.verify_borrow(borrow_token, resource) do
      :ok
    else
      _missing_or_unverifiable -> {:error, UnborrowedAccess.exception(resource: resource)}
    end
  end
end
