defmodule Steward.Resource.Validations.RequireWitness do
  @moduledoc """
  The Witness Pattern, made real (docs/tech_spec.md §4.1: "making the
  borrow checker unbypassable... every Ash action generated by the DSL
  therefore requires a borrow_token in its changeset context. The Spark
  compiler injects this requirement automatically... There is no opt-out
  path at the resource layer"; CLAUDE.md invariant 1: "No unwitnessed
  access").

  `Steward.Resource.Transformers.RequireWitness` attaches one instance of
  this validation, globally, to every resource that uses the
  `Steward.Resource` extension — never hand-wired per action, so an
  author cannot forget it the way a per-action `change` could be
  forgotten.

  Implements `supports/1` for `Ash.Changeset` and `Ash.ActionInput` so
  the same module covers create/update/destroy and generic actions alike
  (see `Steward.Resource.Transformers.RequireWitness` for why `:read` is
  deliberately excluded). Checks only for the *presence* of
  `context[:steward][:borrow_token]` — like `Steward.Changes.EnforceFencing`,
  it trusts a token already in context rather than round-tripping to
  `Steward.ResourceServer` to re-verify liveness; the caller is expected
  to have obtained it from a real `Steward.ResourceServer.acquire/3` (or
  `borrow/3`) call.

  Both `validate/3` and `atomic/3` are implemented identically: the check
  only inspects `context`, never resource attributes, so it needs no
  database expression and is atomic-compatible by construction — no
  `require_atomic? false` needed on account of this validation.
  """

  use Ash.Resource.Validation

  alias Steward.Errors.UnborrowedAccess

  @impl true
  def supports(_opts), do: [Ash.Changeset, Ash.ActionInput]

  @impl true
  def validate(changeset_query_or_input, _opts, _context) do
    check(changeset_query_or_input)
  end

  @impl true
  def atomic(changeset_query_or_input, _opts, _context) do
    check(changeset_query_or_input)
  end

  defp check(changeset_query_or_input) do
    case get_in(changeset_query_or_input.context, [:steward, :borrow_token]) do
      nil ->
        {:error, UnborrowedAccess.exception(resource: changeset_query_or_input.resource)}

      _borrow_token ->
        :ok
    end
  end
end
