defmodule Steward.Repo.Migrations.AddSagaStepIdentity do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create unique_index(:saga_steps, [:saga_id, :step_id],
             name: "saga_steps_unique_saga_step_index"
           )
  end

  def down do
    drop_if_exists unique_index(:saga_steps, [:saga_id, :step_id],
                     name: "saga_steps_unique_saga_step_index"
                   )
  end
end
