defmodule Steward.Repo.Migrations.AddShadowInvoice do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:shadow_invoices, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :external_id, :text, null: false
      add :status, :text, default: "draft"
      add :total_amount, :decimal
      add :amount_paid, :decimal, default: "0"
      add :version, :bigint, default: 0
      add :sync_status, :text, default: "synced"
      add :synced_at, :utc_datetime_usec
    end

    create unique_index(:shadow_invoices, [:external_id],
             name: "shadow_invoices_unique_external_id_index"
           )
  end

  def down do
    drop_if_exists unique_index(:shadow_invoices, [:external_id],
                     name: "shadow_invoices_unique_external_id_index"
                   )

    drop table(:shadow_invoices)
  end
end
