defmodule Steward.Repo.Migrations.AddSagas do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:saga_steps, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :saga_id, :uuid, null: false
      add :step_id, :text, null: false
      add :resource, :text, null: false
      add :resource_id, :text, null: false
      add :action, :text, null: false
      add :status, :text, default: "pending"
      add :disposition, :text
      add :result, :map
      add :error, :map

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create table(:sagas, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
    end

    alter table(:saga_steps) do
      modify :saga_id,
             references(:sagas,
               column: :id,
               name: "saga_steps_saga_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:sagas) do
      add :plan, {:array, :map}, null: false
      add :status, :text, default: "running"
      add :error, :map
      add :attempts, :bigint, default: 0
      add :finished_at, :utc_datetime_usec

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end
  end

  def down do
    alter table(:sagas) do
      remove :updated_at
      remove :inserted_at
      remove :finished_at
      remove :attempts
      remove :error
      remove :status
      remove :plan
    end

    drop constraint(:saga_steps, "saga_steps_saga_id_fkey")

    alter table(:saga_steps) do
      modify :saga_id, :uuid
    end

    drop table(:sagas)

    drop table(:saga_steps)
  end
end
